default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: taskflow_development

test:
  <<: *default
  database: taskflow_test

production:
  <<: *default
  database: taskflow_production
  username: taskflow
  password: <%= ENV["DATABASE_PASSWORD"] %>
